name: E2E test - scaffold command

permissions: { }

on:
  pull_request:
    branches:
      - main
      - 'release-**'

jobs:
  test-scaffold-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Go setup
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Build
        run: |
          make build-linux
          chmod +x ./bin/modulectl-linux
          ls -la ./bin
          mv ./bin/modulectl-linux /usr/local/bin/modulectl
        timeout-minutes: 5
      - name: Run tests
        run: |
          make -C tests/e2e test-scaffold-cmd
        timeout-minutes: 3
