name: E2E test - create command

permissions: { }

on:
  push:
    branches:
      - main
      - 'release-**'
  pull_request:
    branches:
      - main
      - 'release-**'

jobs:
  test-create-cmd:
    runs-on: ubuntu-latest
    env:
      K3D_VERSION: v5.4.7
      MODULE_TEMPLATE_VERSION: 1.0.0
      OCI_REPOSITORY_URL: http://k3d-oci.localhost:5001
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout template-operator
        uses: actions/checkout@v5
        with:
          repository: kyma-project/template-operator
          path: template-operator

      - name: Get template-operator latest commit hash
        working-directory: template-operator
        run: echo "TEMPLATE_OPERATOR_LATEST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Go setup
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Build
        run: |
          make build-linux
          chmod +x ./bin/modulectl-linux
          ls -la ./bin
          mv ./bin/modulectl-linux /usr/local/bin/modulectl
        timeout-minutes: 5
      - name: Install k3d and create registry
        run: |
          wget -qO - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=$K3D_VERSION bash
          k3d registry create oci.localhost --port 5001
      - name: Run tests
        run: |
          make -C tests/e2e test-create-cmd
        timeout-minutes: 3
